apiVersion: v1
kind: Service
metadata:
  name: aquapump-backend
  namespace: aquapump
  labels:
    app: aquapump-backend
spec:
  type: ClusterIP
  selector:
    app: aquapump-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
