apiVersion: v1
kind: Service
metadata:
  name: aquapump-frontend
  namespace: aquapump
  labels:
    app: aquapump-frontend
spec:
  type: ClusterIP
  selector:
    app: aquapump-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
