backend:
  envSecrets:
    SUPABASE_URL: "secret:prod/aquapump#SUPABASE_URL"
    SUPABASE_SERVICE_ROLE_KEY: "secret:prod/aquapump#SUPABASE_SERVICE_ROLE_KEY"
    AI_API_KEY: "secret:prod/aquapump#AI_API_KEY"

frontend:
  envSecrets:
    VITE_REACT_APP_SUPABASE_URL: "secret:prod/aquapump#SUPABASE_URL"
