{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.backend.data }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.backend.name }}
spec:
  refreshInterval: {{ default "1h" .Values.externalSecrets.backend.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.backend.secretName }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.backend.data | nindent 4 }}
---
{{- end }}
{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.frontend.data }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.frontend.name }}
spec:
  refreshInterval: {{ default "1h" .Values.externalSecrets.frontend.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.frontend.secretName }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.frontend.data | nindent 4 }}
{{- end }}
