{{- $frontend := .Values.ingress.frontend -}}
{{- if $frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "aquapump.frontendFullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aquapump.frontendName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with $frontend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $frontend.className }}
  ingressClassName: {{ $frontend.className }}
  {{- end }}
  rules:
    {{- range $frontend.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "aquapump.frontendFullname" $ }}
                port:
                  number: {{ $.Values.frontend.service.port }}
          {{- end }}
    {{- end }}
  {{- if $frontend.tls }}
  tls:
    {{- toYaml $frontend.tls | nindent 4 }}
  {{- end }}
{{- end }}
