{{- $root := . -}}
{{- $ing := $root.Values.ingress -}}
{{- if $ing.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "aquapump.fullname" $root }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "aquapump.name" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
{{- if $ing.annotations }}
  annotations:
{{ toYaml $ing.annotations | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ $ing.className | default "alb" }}
  rules:
  {{- range $host := $ing.hosts }}
    - host: {{ $host.host | quote }}
      http:
        paths:
        {{- range $path := $host.paths }}
          - path: {{ $path.path | quote }}
            pathType: {{ $path.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $path.service.name }}
                port:
                  number: {{ $path.service.port }}
        {{- end }}
  {{- end }}
{{- if $ing.tls }}
  tls:
{{ toYaml $ing.tls | indent 4 }}
{{- end }}
{{- end }}
