{{- $backend := .Values.ingress.backend -}}
{{- if $backend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "aquapump.backendFullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aquapump.backendName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with $backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $backend.className }}
  ingressClassName: {{ $backend.className }}
  {{- end }}
  rules:
    {{- range $backend.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "aquapump.backendFullname" $ }}
                port:
                  number: {{ $.Values.backend.service.port }}
          {{- end }}
    {{- end }}
  {{- if $backend.tls }}
  tls:
    {{- toYaml $backend.tls | nindent 4 }}
  {{- end }}
{{- end }}
