{{- $ing := .Values.ingress -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "aquapump.fullname" . }}-ingress
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "aquapump.name" . }}
  annotations:
    {{- if $ing.annotations }}
{{ toYaml $ing.annotations | indent 4 }}
    {{- end }}
    {{- if and $ing.tls.enabled $ing.tls.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ $ing.tls.clusterIssuer | quote }}
    {{- end }}

spec:
  ingressClassName: {{ $ing.className | default "nginx" }}
  rules:
    {{- /* frontend hosts (simple list of strings) */}}
    {{- range $host := $ing.frontend.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "aquapump.frontendFullname" $ }}
                port:
                  number: {{ $.Values.frontend.service.port }}
    {{- end }}

    {{- /* backend host (single string) */}}
    - host: {{ $ing.backend.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "aquapump.backendFullname" . }}
                port:
                  number: {{ $.Values.backend.service.port }}

  {{- if $ing.tls.enabled }}
  tls:
    - secretName: {{ $ing.tls.frontendSecretName }}
      hosts:
        {{- range $host := $ing.frontend.hosts }}
        - {{ $host | quote }}
        {{- end }}
    - secretName: {{ $ing.tls.backendSecretName }}
      hosts:
        - {{ $ing.backend.host | quote }}
  {{- end }}
