---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aquapump.frontendFullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aquapump.frontendName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "aquapump.frontendName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
