{{- range $name, $component := .Values.components }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $.Release.Name $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-%s" $.Release.Name $name }}
    app.kubernetes.io/component: {{ $name }}
spec:
  selector:
    app.kubernetes.io/name: {{ printf "%s-%s" $.Release.Name $name }}
  type: {{ $component.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $component.service.port | default $component.containerPort }}
      targetPort: {{ $component.service.targetPort | default $component.containerPort }}
      protocol: TCP
      name: http
{{- if $component.service.additionalPorts }}
{{ toYaml $component.service.additionalPorts | nindent 4 }}
{{- end }}
{{- end }}
