---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aquapump.backendFullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aquapump.backendName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "aquapump.backendName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
