apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aquapump-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: aquapump-dev
    app.kubernetes.io/part-of: aquapump
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: aquapump
  revisionHistoryLimit: 5
  source:
    repoURL: https://github.com/orivann/aquapump.git
    targetRevision: main
    path: deploy/helm/aquapump
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
      releaseName: aquapump-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: aquapump-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
