apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aquapump-dev
  namespace: argocd
spec:
  project: aquapump
  source:
    repoURL: https://github.com/orivann/aquapump.git
    targetRevision: main
    path: deploy/helm/aquapump
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: aquapump-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
