apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aquapump-staging
  namespace: argocd
spec:
  project: aquapump
  source:
    repoURL: https://github.com/orivann/aquapump.git
    targetRevision: main
    path: deploy/helm/aquapump
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: aquapump-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
