apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aquapump-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/orivann/aquapump.git
    targetRevision: main
    path: deploy/helm/aquapump
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: aquapump
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 10m
